import CatDonation from "@/components/CatDonation";
import Head from "next/head";
import Link from "next/link";

function ListLink({ url }: { url: string }) {
    return (
        <li>
            <Link href={`/${url}`}>🐈 {url}</Link>
        </li>
    );
}

export default function Home() {
    return (
        <>
            <Head>
                <title>🐈‍⬛ Next Test</title>
                {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>🐈‍⬛ real cat page on Next 🐈‍⬛</h1>
                <ul>
                    <ListLink url="neko"></ListLink>
                    <ListLink url="neko/101"></ListLink>
                </ul>
                <CatDonation />
            </main>
        </>
    );
}
